# Generated by Django 5.2.7 on 2025-11-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrfAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
